[
uuid(6876e464-0a80-4684-9fa6-bd8386c15060),
version(1.0),
implicit_handle (handle_t g_LIServerRPCInterfaceHandle)
]
interface LIServerRPCInterface
{
	const unsigned int LISMaxStringLength = 1024;
	void LISPing(void);
	void LISSetPosition([in] int x, [in] int y);
	void LISHandleKey([in] int keyCode, [out, ref] boolean *hasHandled);
	void LISCompositionString([out, string, size_is(LISMaxStringLength)] wchar_t *compositionString);

	void LISNextAvailableClientRPCEndpointName([out, string, size_is(LISMaxStringLength)] wchar_t *endpointName);
	void LISSetClientRPCEndpointName([in, string] const wchar_t *endpointName);
	void LISEndCurrentClientRPCEndpoint(void);
}
