#!/bin/bash
echo "Start postflight script"
VERSION_FOR_INSTALLER="2528";
URL="http://tw.rd.yahoo.com/referurl/keykey/client/installer/end/${VERSION_FOR_INSTALLER}M104/*http://tw.yimg.com/i/tw/download/ykkimg/blank.gif"
/usr/bin/curl -L -A "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)" $URL  > /dev/null
echo $SCRIPT_NAME: launching html help
open "/Library/Components/Yahoo! KeyKey.bundle/Contents/SharedSupport/KeyKeyServer.app/Contents/SharedSupport/InstallerHelp.app"
echo "End postflight script"
exit 0
