[
uuid(6876e464-0a80-4684-9fa6-bd8386c15060),
version(1.0),
implicit_handle (handle_t g_LIClientRPCInterfaceHandle)
]
interface LIClientRPCInterface
{
	const unsigned int LICMaxStringLength = 1024;
	void LICSendString([in, string] const wchar_t *externalString);
}
