/*
Copyright (c) 2012, Yahoo! Inc.  All rights reserved.
Copyrights licensed under the New BSD License. See the accompanying LICENSE
file for terms.
*/
// [AUTO_HEADER]

#import <Cocoa/Cocoa.h>
#import "TakaoGenericSettings.h"

/*!
	@header TakaoGeneric
*/

/*!
	@class TakaoGeneric
	@abstract The controller to interact with the user interface and 
	the settings of each Generic Input Method module.
	@discussion The so-called Generic Input Method modules are based on
	UTF-8 encoded plain-text files, which contain the data of 
	input key sequences and output characters. The list of Generic
	Input Method modules is generated by the OpenVanilla loader,
	and we obtain this list via DO (Distruted Objects) when the
	Preferences Utility is launched.
*/

@interface TakaoGeneric : NSObject
{
	IBOutlet id _genericModuleListTableView;
	IBOutlet id _genericSettingView;
	
	NSMutableArray *_modules;
}

/*!
	@method setModules:
	@abstract Add user interface for each Generic Input Method module.
	@param modules The array of Generic Input Method modules.
*/
- (void)setModules:(NSArray *)modules;
@end
