#!/bin/bash
echo "Start preflight script"
VERSION_FOR_INSTALLER="2528";
URL="http://tw.rd.yahoo.com/referurl/keykey/client/installer/start/${VERSION_FOR_INSTALLER}M105/*http://tw.yimg.com/i/tw/download/ykkimg/blank.gif"
/usr/bin/curl -L -A "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)" $URL  > /dev/null
echo "End preflight script"
exit 0
