/*
Copyright (c) 2012, Yahoo! Inc.  All rights reserved.
Copyrights licensed under the New BSD License. See the accompanying LICENSE
file for terms.
*/
    m["F0"] = "F0#";
    m["5_"] = "F0#";
    m["u?"] = "F0#";
    m["L_"] = "L_#";
    m["=@"] = "L_#";
    m["p?"] = "p?#";
    m["<C"] = "p?#";
    m["{J"] = "p?#";
    m[":b"] = ":b#";
    m["zB"] = ":b#";
    m["Cb"] = "Cb#";
    m["rq"] = "Cb#";
    m["mJ"] = "mJ#";
    m["\\y"] = "mJ#";
    m["4W"] = "4W#";
    m["cf"] = "4W#";
    m["cp"] = "cp#";
    m["lq"] = "cp#";
    m["qA"] = "qA#";
    m["zB"] = "qA#";
    m["N0"] = "N0#";
    m["]O"] = "N0#";
    m["OP"] = "OP#";
    m["|U"] = "OP#";
    m["k@"] = "k@#";
    m["Zo"] = "k@#";
    m["p1"] = "p1#";
    m["PA"] = "p1#";
    m["K_"] = "K_#";
    m["ZR"] = "K_#";
    m["gg"] = "gg#";
    m["2P"] = "gg#";
    m["Eb"] = "Eb#";
    m["L`"] = "Eb#";
    m["R3"] = "R3#";
    m["|?"] = "R3#";
    m["r4"] = "r4#";
    m["2T"] = "r4#";
    m["tI"] = "tI#";
    m["{@"] = "tI#";
    m["RO"] = "RO#";
    m["an"] = "RO#";
    m["V>"] = "V>#";
    m["6N"] = "V>#";
