#!/bin/bash
echo "Start postflight script"

IMK="/Library/Input Methods/Yahoo! KeyKey.app/Contents/MacOS/Yahoo! KeyKey"
TSM="/Library/Components/Yahoo! KeyKey.bundle/Contents/SharedSupport/KeyKeyServer.app/Contents/MacOS/KeyKeyServer"

if [ -e "$IMK" ]
then
    "$IMK" reload
else
    if [ -e "$TSM" ]
    then
        "$TSM" reload
    fi    
fi

exit 0
